#!/usr/bin/env bash
# =============================================================================
# Generate one ServiceMonitor per CircleGuard service.
#
# The output is committed to this directory so reviewers and `kubectl apply`
# don't depend on the script — re-run it only if you add or rename a service.
#
# Usage:
#   ./gen.sh           # regenerate all *.yaml in the current dir
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SERVICES=(
  auth
  dashboard
  file
  form
  gateway
  identity
  notification
  promotion
)

for svc in "${SERVICES[@]}"; do
  out="${SCRIPT_DIR}/${svc}-servicemonitor.yaml"
  cat > "${out}" <<EOF
# AUTO-GENERATED by gen.sh — edit gen.sh, not this file.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: circleguard-${svc}
  namespace: observability
  labels:
    # Picked up by Prometheus because kube-prometheus-stack values.yaml
    # sets serviceMonitorSelector to matchLabels { monitoring: enabled }.
    monitoring: enabled
    app.kubernetes.io/part-of: circleguard
    app.kubernetes.io/component: ${svc}
spec:
  # Look for Service objects in any circleguard-* namespace whose Pods
  # carry the standard app.kubernetes.io/name label.
  namespaceSelector:
    matchNames:
      - circleguard-dev
      - circleguard-stage
      - circleguard-master
  selector:
    matchLabels:
      app.kubernetes.io/name: circleguard-${svc}-service
  endpoints:
    - port: http              # Service must expose an "http" named port
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
      relabelings:
        # Promote the Pod's app label as the "app" series label so all our
        # PromQL queries can rely on a single, short label name.
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
          targetLabel: app
        - action: replace
          sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
EOF
  echo "wrote ${out}"
done
